### ISSUE TITLE
HttpDataSourceException on Android P

### ISSUE THREAD

**Issue by cemrich** [cemrich/zapp#115]
```
Caused by: com.google.android.exoplayer2.upstream.HttpDataSource$HttpDataSourceException: Unable to connect to http://nrodl.zdf.de/none/3sat/18/06/180610_andalusien_wo_spaniens_seele_wohnt_2_ard/1/180610_andalusien_wo_spaniens_seele_wohnt_2_ard_2328k_p35v13.mp4
        at com.google.android.exoplayer2.upstream.DefaultHttpDataSource.open(DefaultHttpDataSource.java:194)
        at com.google.android.exoplayer2.upstream.DefaultDataSource.open(DefaultDataSource.java:147)
        at com.google.android.exoplayer2.source.ExtractorMediaPeriod$ExtractingLoadable.load(ExtractorMediaPeriod.java:841)
        at com.google.android.exoplayer2.upstream.Loader$LoadTask.run(Loader.java:308)
        at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1167)
        at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:641)
        at java.lang.Thread.run(Thread.java:764)
```

**Comment by cemrich** [comment]
https://developer.android.com/training/articles/security-config
