### ISSUE TITLE
Fehler beim laden der Mediathek

### ISSUE THREAD

**Issue by cyberpunkbln** [cemrich/zapp#82]
Hallo,

live-streams funktionieren perfekt aber leider erscheint bei Mediathek ein Hinweis das sie nicht geladen werden konnte und ich meine Internetverbindung untersuchen soll:).

Android 4.4.2

Original Mediathek funktioniert vom ZDF als Beispiel.

thx

**Comment by cemrich** [comment]
Danke für das Ticket!

I can reproduce this error on the emulator. It is a SSL error again - possibly related to #67 

```
java.net.UnknownServiceException: Unable to find acceptable protocols. isFallback=false, modes=[ConnectionSpec(cipherSuites=[TLS_DHE_RSA_WITH_AES_128_GCM_SHA256], tlsVersions=[TLS_1_3, TLS_1_2, TLS_1_1, TLS_1_0], supportsTlsExtensions=true)], supported protocols=[SSLv3, TLSv1]
                                                                                         at okhttp3.internal.connection.ConnectionSpecSelector.configureSecureSocket(ConnectionSpecSelector.java:73)
                                                                                         at okhttp3.internal.connection.RealConnection.connectTls(RealConnection.java:274)
                                                                                         at okhttp3.internal.connection.RealConnection.establishProtocol(RealConnection.java:251)
                                                                                         at okhttp3.internal.connection.RealConnection.connect(RealConnection.java:151)
                                                                                         at okhttp3.internal.connection.StreamAllocation.findConnection(StreamAllocation.java:192)
                                                                                         at okhttp3.internal.connection.StreamAllocation.findHealthyConnection(StreamAllocation.java:121)
                                                                                         at okhttp3.internal.connection.StreamAllocation.newStream(StreamAllocation.java:100)
                                                                                         at okhttp3.internal.connection.ConnectInterceptor.intercept(ConnectInterceptor.java:42)
                                                                                         at okhttp3.internal.http.RealInterceptorChain.proceed(RealInterceptorChain.java:92)
                                                                                         at okhttp3.internal.http.RealInterceptorChain.proceed(RealInterceptorChain.java:67)
                                                                                         at okhttp3.internal.cache.CacheInterceptor.intercept(CacheInterceptor.java:93)
                                                                                         at okhttp3.internal.http.RealInterceptorChain.proceed(RealInterceptorChain.java:92)
                                                                                         at okhttp3.internal.http.RealInterceptorChain.proceed(RealInterceptorChain.java:67)
                                                                                         at okhttp3.internal.http.BridgeInterceptor.intercept(BridgeInterceptor.java:93)
                                                                                         at okhttp3.internal.http.RealInterceptorChain.proceed(RealInterceptorChain.java:92)
                                                                                         at okhttp3.internal.http.RetryAndFollowUpInterceptor.intercept(RetryAndFollowUpInterceptor.java:120)
                                                                                         at okhttp3.internal.http.RealInterceptorChain.proceed(RealInterceptorChain.java:92)
                                                                                         at okhttp3.internal.http.RealInterceptorChain.proceed(RealInterceptorChain.java:67)
                                                                                         at okhttp3.RealCall.getResponseWithInterceptorChain(RealCall.java:185)
                                                                                         at okhttp3.RealCall$AsyncCall.execute(RealCall.java:135)
                                                                                         at okhttp3.internal.NamedRunnable.run(NamedRunnable.java:32)
                                                                                         at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1112)
                                                                                         at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:587)
                                                                                         at java.lang.Thread.run(Thread.java:841)
```

**Comment by cemrich** [comment]
With the next update I'll show a more specific warning. 

The underlying error is too complicated to fix and only affects old Android versions, so I won't fix it for now. Pull requests however are very welcome.

**Comment by cyberpunkbln** [comment]
thx
i understand, which android versions are usable? 5 and higher?

**Comment by cemrich** [comment]
Yes, I think Android 5 and up should work fine.
The updated version 1.8.1 will be released soon on F-Droid.
